NuestroMundo/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
	url(r'^(?P<nombre_pais>[A-Z|a-z]+)/$', views.pais, name='paises'),
    url(r'^ciudades/(?P<id_ciudad>[0-9]+)$', views.ciudad, name='ciudades'),
    url(r'^idiomas/(?P<idioma_nombre>.+)$', views.idioma, name='idiomas'),
]

NuestroMundo_Project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^nuestromundo/', include('NuestroMundo.urls', namespace="NuestroMundo")),
    url(r'^NuestroMundo/', include('NuestroMundo.urls', namespace="NuestroMundo")),
    url(r'^admin/', include(admin.site.urls)),	
]

NuestroMundo/models.py
from django.db import models

# Create your models here.
class Pais(models.Model):
    codigo = models.CharField(max_length=3)
    nombre = models.CharField(max_length=60)
    continente = models.CharField(max_length=60)
    region = models.CharField(max_length=40)
    area = models.DecimalField(max_digits=22, decimal_places=2)
    independencia = models.IntegerField(default=1948)
    poblacion = models.IntegerField(default=1000000)
    esperanza_vida = models.DecimalField(max_digits=3, decimal_places=1)
    PIB = models.DecimalField(max_digits=18, decimal_places=2)
    PIB_anterior = models.DecimalField(max_digits=18, decimal_places=2)
    nombre_local = models.CharField(max_length=60)
    tipo_gobierno = models.CharField(max_length=80)
    lider_estado = models.CharField(max_length=60)
    capital = models.IntegerField()
    codigo_corto = models.CharField(max_length=2)
    def __str__(self):              
        return self.nombre + ", " + self.continente
	
class Ciudad(models.Model):
    nombre = models.CharField(max_length=60)
    codigo_pais = models.CharField(max_length=3)
    distrito = models.CharField(max_length=60)
    poblacion = models.IntegerField(default=10000)
    def __str__(self):              
        return self.nombre
	
class Idioma_Pais(models.Model):
    codigo_pais = models.CharField(max_length=3)
    idioma = models.CharField(max_length=40)	
    porcentaje = models.DecimalField(max_digits=3, decimal_places=1)
    def __str__(self):              
        return self.idioma

class Idioma(models.Model):
    nombre = models.CharField(max_length=40)
    def __str__(self):              
        return self.nombre

NuestroMundo/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Pais, Ciudad, Idioma_Pais, Idioma

def index(request):
    paises = Pais.objects.order_by('nombre')
    context = {'paises' : paises}
    return render(request, 'nuestromundo/index.html', context)
	
def pais(request, nombre_pais):
    pais = Pais.objects.get(codigo=nombre_pais)
    ciudades = Ciudad.objects.filter(codigo_pais=nombre_pais)
    capital = Ciudad.objects.get(pk=pais.capital)
    idiomas_pais = Idioma_Pais.objects.filter(codigo_pais=pais.codigo)
    context = {'pais' : pais, 'ciudades' : ciudades, 'capital' : capital, 'idiomas_pais' : idiomas_pais}
    return render(request, 'nuestromundo/pais.html', context)

def ciudad(request, id_ciudad):    
    ciudad = Ciudad.objects.get(pk=id_ciudad)
    pais = Pais.objects.get(codigo=ciudad.codigo_pais)
    context = {'ciudad' : ciudad, 'pais' : pais}
    return render(request, 'nuestromundo/ciudad.html', context)

def idioma(request, idioma_nombre):
    idioma = Idioma.objects.get(nombre=idioma_nombre)
    paises = Pais.objects.order_by('nombre')
    idioma_paises = Idioma_Pais.objects.filter(idioma=idioma.nombre)
    context = {'idioma' : idioma, 'idioma_paises' : idioma_paises, 'paises' : paises}
    return render(request, 'nuestromundo/idioma.html', context)

NuestroMundo/templates/NuestroMundo/ciudad.html
{% load staticfiles %}
<head>
    <title>Nuestro Mundo: {{ ciudad.nombre }}, {{ pais.nombre }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'NuestroMundo/style/estilo.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'NuestroMundo/style/mundo.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'NuestroMundo/style/ciudad.css' %}" />
</head>
<div class="barra-controles">
    <a href="{% url 'NuestroMundo:index' %}">
        <div class="control">
            <p class="icono-control"></p>
            <p class="titulo-control">Nuestro Mundo</p>
        </div>
    </a>
</div>
<p class="titulo-seccion">{{ ciudad.nombre }}</p>
<div class="informacion">
    <div class="columna">
        <h3><u>Pais:</u> <a href="{% url 'NuestroMundo:paises' pais.codigo %}">{{ pais.nombre }} </a></h3>
        {% if pais.capital == ciudad.id %}
            <h3><u>Es la ciudad capital de su país</u></h3>
        {% endif %}
        <h3><u>Distrito:</u> {{ ciudad.distrito }} </h3>
        <h3><u>Poblacion:</u> {{ ciudad.poblacion }} personas</h3>
    </div>
</div>

NuestroMundo/templates/NuestroMundo/idioma.html
{% load staticfiles %}
<head>
    <title>Nuestro Mundo: {{ idioma.nombre }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'NuestroMundo/style/estilo.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'NuestroMundo/style/mundo.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'NuestroMundo/style/idioma.css' %}" />
</head>
<div class="barra-controles">
    <a href="{% url 'NuestroMundo:index' %}">
        <div class="control">
            <p class="icono-control"></p>
            <p class="titulo-control">Nuestro Mundo</p>
        </div>
    </a>
</div>
<p class="titulo-seccion">{{ idioma.nombre }}</p>

{% if idioma_paises %}
    {% for idioma_pais in idioma_paises %}
        {% for pais in paises %}
            {% if pais.codigo == idioma_pais.codigo_pais %}
                <a href="{% url 'NuestroMundo:paises' idioma_pais.codigo_pais %}" class="pais">{{ pais.nombre }} - {{ idioma_pais.porcentaje }}%</a>
            {% endif %}
        {% endfor %}
    {% endfor %}
{% else %}
	<p class="error">No hay paises que hablen este idioma D:</p>
{% endif %}

NuestroMundo/templates/NuestroMundo/index.html
{% load staticfiles %}
<head>    
    <title>Nuestro Mundo</title>
    <link rel="stylesheet" type="text/css" href="{% static 'NuestroMundo/style/estilo.css' %}" />
</head>

{% if paises %}
    <div class="barra-controles">
        <!-- <div class="control">
            <p class="icono-control"></p>
            <p class="titulo-control">Modo lista</p>
        </div> -->
        <a href="{% url 'NuestroMundo:index' %}">
            <div class="control">
                <p class="icono-control"></p>
                <p class="titulo-control">Nuestro Mundo</p>
            </div>
        </a>
        <!-- <div class="control">
            <p class="icono-control"></p>
            <p class="titulo-control">Filtrar</p>
        </div> -->
    </div>
	{% for pais in paises %}
		<a href="{% url 'NuestroMundo:paises' pais.codigo %}"><div class="pais"><img src= "{% static "NuestroMundo/images/banderas/" %}{{ pais.codigo_corto }}.png" />{{ pais.nombre }}</div></a>
	{% endfor %}
{% else %}
	<p class="error">No hay paises en nuestro mundo D:</p>
{% endif %}

NuestroMundo/templates/NuestroMundo/pais.html
{% load staticfiles %}
<head>
    <title>Nuestro Mundo: {{ pais.nombre }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'NuestroMundo/style/estilo.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'NuestroMundo/style/mundo.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'NuestroMundo/style/pais.css' %}" />
</head>
<div class="barra-controles">
    <a href="{% url 'NuestroMundo:index' %}">
        <div class="control">
            <p class="icono-control"></p>
            <p class="titulo-control">Nuestro Mundo</p>
        </div>
    </a>
</div>
<img src= "{% static "NuestroMundo/images/banderas/" %}{{ pais.codigo_corto }}.png" />
<div class="informacion">
    <h2>{{ pais.nombre }}</h2>
    <div class="columna">
        <h3><u>Codigo:</u> {{ pais.codigo }}</h3>
        <h3><u>Codigo corto:</u> {{ pais.codigo_corto }}</h3>
        <h3><u>Region:</u> {{ pais.region }}</h3>
        <h3><u>Continente:</u> {{ pais.continente }}</h3>
        <h3><u>Capital:</u> {{ capital }}</h3>
        <h3><u>Area:</u> {{ pais.area }}</h3>
        <h3><u>Año independencia:</u> {{ pais.independencia }}</h3>
    </div>
    <div class="columna">
        <h3><u>Poblacion:</u> {{ pais.poblacion }} personas</h3>
        <h3><u>Esperanza vida:</u> {{ pais.esperanza_vida }} años</h3>
        <h3><u>PIB:</u> {{ pais.PIB }} $</h3>
        <h3><u>PIB anterior:</u> {{ pais.PIB_anterior }} $</h3>
        <h3><u>Nombre local:</u> {{ pais.nombre_local }}</h3>
        <h3><u>Tipo de gobierno:</u> {{ pais.tipo_gobierno }}</h3>
        <h3><u>Lider de estado:</u> {{ pais.lider_estado }}</h3>
    </div>
</div>
<p class="titulo-seccion">Idiomas:</p>
{% if idiomas_pais %}
    {% for idioma in idiomas_pais %}
        <a href="{% url 'NuestroMundo:idiomas' idioma.idioma %}" class="idioma">{{ idioma.idioma }} - {{ idioma.porcentaje }}%</a>
    {% endfor %}
{% else %}
	<p class="error">No hay idiomas en este pais D:</p>
{% endif %}

<p class="titulo-seccion">Ciudades:</p>
{% if ciudades %}
    {% for ciudad in ciudades %}
        <a href="{% url 'NuestroMundo:ciudades' ciudad.id %}" class="ciudad">{{ ciudad.nombre }}</a>
    {% endfor %}
{% else %}
	<p class="error">No hay ciudades en este pais D:</p>
{% endif %}